media:
  input: content/_uploads
  output: /uploads
content:
  - name: wires
    label: Wires
    type: collection
    path: 'content/_wire'
    view:
      fields: [ date, slug ]
      primary: slug
    fields:
      - name: date
        label: Date
        type: date
      - name: slug
        label: Slug
        type: string
      - name: title
        label: Title
        type: string
        required: false
      - name: link
        label: Link
        type: string
        required: false
      - name: body
        label: Body
        type: rich-text
      - name: highlighted
        label: Highlighted
        type: boolean
        default: false
      - name: published
        label: Published
        type: boolean
        default: true
  - name: releases
    label: Releases
    type: collection
    path: 'content/_releases'
    view:
      fields: [ title, artist, year ]
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: artist
        label: Artist
        type: string
        required: true
      - name: year
        label: Year
        type: string
        required: true
      - name: image
        label: Artwork
        type: image
        required: true
        options:
          path: releases
      - name: listen
        label: Listen Link
        type: string
        required: false
      - name: role
        label: Role
        type: string
        required: false
      - name: type
        label: Type
        type: select
        required: true
        options:
          values: [ LP, EP, single ]
      - name: featured
        label: Featured
        type: boolean
        default: false