backend:
  name: github
  repo: spencertweedy/spencertweedy.com
  base_url: https://spoonauth.glitch.me
  branch: main
media_folder: "content/_uploads" # Tells Netlify CMS where to read/write uploads in the source folder
public_folder: "/uploads" # Tells Netlify CMS where to read uploads in the ouput folder
display_url: "https://spencertweedy.com" # Used in the UI
# Define collections (must manually keep up-to-date with site generator config)
collections:
  - name: "Wire Service"
    label: "Wire Service"
    label_singular: "Wire"
    folder: "content/_wire"
    identifier_field: slug
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/_posts"
    editor:
        preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Publish Location", name: "location", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "observations" # Used in routes, e.g., /admin/collections/blog
    label: "Observations" # Used in the UI
    label_singular: "Observations Post" # Used in the UI
    folder: "content/_observations" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    slug: "{{datestamp}}" # Observation post files that Netlify CMS creates will use the `datestamp` field as their slug
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "Observations YYYY-MM-DD"}
      - {label: "Datestamp", name: "datestamp", widget: "datetime", default: "", format: "YYYYMMDD", dateFormat: "LL", timeFormat: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image caption", name: "image_caption", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "releases" # Used in routes, e.g., /admin/collections/blog
    label: "Releases" # Used in the UI
    label_singular: "Release" # Used in the UI
    folder: "content/_releases" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Listen URL", name: "listen", widget: "string", required: false}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "select", options: ["single", "EP", "LP"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
